### ISSUE TITLE
The Colab link appears to be non-functional

### ISSUE THREAD

**Issue by format37** [AhmedImtiazPrio/splinecam#1]
https://bit.ly/splinecam-demo

**Comment by AhmedImtiazPrio** [comment]
It seems to be working for me. Can you try this and check?

https://colab.research.google.com/drive/1gkHZI9BztH3N4qtu4LjTnFb5RCV2nq4d

**Comment by format37** [comment]
> It seems to be working for me. Can you try this and check?
> 
> https://colab.research.google.com/drive/1gkHZI9BztH3N4qtu4LjTnFb5RCV2nq4d

Yes. This link works!
